"""Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms."""

def func():
	n = 1
	total = 0
	def fib(n):
		if n == 1:
			return 0
		elif n == 2:
			return 1
		else:
			return fib(n-2) + fib(n-1)
	m = 0
	while m <= 4000000:
		if m % 2 == 0:
			total += m
		n += 1
		m = fib(n)
	return total
